// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwysq9JYE336LiQ3cD5Bv22iOGyPRveLI',
    appId: '1:1019599778859:web:a62fd7fdd4b08bcfb4266e',
    messagingSenderId: '1019599778859',
    projectId: 'servicebid-e5b1f',
    authDomain: 'servicebid-e5b1f.firebaseapp.com',
    storageBucket: 'servicebid-e5b1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZemrBLZx9-MCS0FFwxsTHBLxBoaXSVo',
    appId: '1:1019599778859:android:3332e39a67daa54ab4266e',
    messagingSenderId: '1019599778859',
    projectId: 'servicebid-e5b1f',
    storageBucket: 'servicebid-e5b1f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_IY9aKz3mdkJUybbwUbYVPKGexzRq37Y',
    appId: '1:1019599778859:ios:3fd04620bb215f6eb4266e',
    messagingSenderId: '1019599778859',
    projectId: 'servicebid-e5b1f',
    storageBucket: 'servicebid-e5b1f.firebasestorage.app',
    iosBundleId: 'com.example.servicebid',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_IY9aKz3mdkJUybbwUbYVPKGexzRq37Y',
    appId: '1:1019599778859:ios:3fd04620bb215f6eb4266e',
    messagingSenderId: '1019599778859',
    projectId: 'servicebid-e5b1f',
    storageBucket: 'servicebid-e5b1f.firebasestorage.app',
    iosBundleId: 'com.example.servicebid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwysq9JYE336LiQ3cD5Bv22iOGyPRveLI',
    appId: '1:1019599778859:web:e596a52f28b0dd54b4266e',
    messagingSenderId: '1019599778859',
    projectId: 'servicebid-e5b1f',
    authDomain: 'servicebid-e5b1f.firebaseapp.com',
    storageBucket: 'servicebid-e5b1f.firebasestorage.app',
  );
}
